// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd4dbosoKDLWay7jXf2LnmGzjsyDLMVLA',
    appId: '1:8236996799:web:2958ecd5c0d93f336e0e0a',
    messagingSenderId: '8236996799',
    projectId: 'pomoductive-backend',
    authDomain: 'pomoductive-backend.firebaseapp.com',
    storageBucket: 'pomoductive-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWG337_AO1dBMazajqbvoENP-6NFPlxFI',
    appId: '1:8236996799:ios:5078abcbfd81f0ff6e0e0a',
    messagingSenderId: '8236996799',
    projectId: 'pomoductive-backend',
    storageBucket: 'pomoductive-backend.firebasestorage.app',
    iosBundleId: 'com.example.flutterPomoductive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWG337_AO1dBMazajqbvoENP-6NFPlxFI',
    appId: '1:8236996799:ios:5078abcbfd81f0ff6e0e0a',
    messagingSenderId: '8236996799',
    projectId: 'pomoductive-backend',
    storageBucket: 'pomoductive-backend.firebasestorage.app',
    iosBundleId: 'com.example.flutterPomoductive',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGkLGaP0FpKb1AsSrAs8IxBQU-CDgU1mg',
    appId: '1:8236996799:android:6af50adfd3a4dc9b6e0e0a',
    messagingSenderId: '8236996799',
    projectId: 'pomoductive-backend',
    storageBucket: 'pomoductive-backend.firebasestorage.app',
  );

}
